/**
 * Copyright 2013 Snehasish Roy
 *
 * This file is part of CodeIt! ©.
 *
 * CodeIt! © is free software: you can redistribute it and/or modify it under
 * the terms of the GNU General Public License as published by the Free Software
 * Foundation, either version 3 of the License, or (at your option) any later
 * version.
 *
 * CodeIt! © is distributed in the hope that it will be useful, but WITHOUT ANY
 * WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR
 * A PARTICULAR PURPOSE. See the GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License along with
 * CodeIt! ©. If not, see <http://www.gnu.org/licenses/>.
 */
package workingwithideone;

/**
 * QueryInProgress.java Purpose: Displays the query panel
 *
 * @author Snehasish Roy
 * @version 1.0 17/06/2013
 */
public class SubmissionQuery extends javax.swing.JPanel {

    private static final long serialVersionUID = 1L;
    CodeIt ref;

    /**
     * Enable and sets the text of the Notification Label
     */
    public void setNotification(String text) {
        jLabel1.setText(text);
    }

    /**
     * Disable the indeterminate mode of the JProgressBar
     */
    public void enableProgressBar(boolean val) {
        jProgressBar1.setIndeterminate(val);
    }

    /**
     * Initializes the GUI
     */
    public SubmissionQuery(CodeIt reference) {
        initComponents();
        this.ref = reference;
    }

    //Auto generated by NetBeans IDE
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jProgressBar1 = new javax.swing.JProgressBar();
        jLabel1 = new javax.swing.JLabel();

        setLayout(new java.awt.GridBagLayout());

        jProgressBar1.setCursor(new java.awt.Cursor(java.awt.Cursor.WAIT_CURSOR));
        jProgressBar1.setIndeterminate(true);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 359;
        gridBagConstraints.ipady = 19;
        gridBagConstraints.insets = new java.awt.Insets(13, 57, 0, 0);
        add(jProgressBar1, gridBagConstraints);

        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel1.setText("Fetching list of available languages. Please wait :)");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(0, 90, 0, 32);
        add(jLabel1, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JProgressBar jProgressBar1;
    // End of variables declaration//GEN-END:variables
}
